### ISSUE TITLE
RGB or Neopixel Pins?

### ISSUE THREAD

**Issue by acguardia** [makerbase-mks/MKS-Monster8#1]
No RGB or Neopixel pins out?
No expansion Pins?

**Comment by jangrewe** [comment]
@mks-viva Would PA9/PA10 also correspond to the UART TX/RX on a V2 board?

**Edit:** Nevermind, i think i found the answer...

<img width="632" height="423" alt="Image" src="https://github.com/user-attachments/assets/f24a4b70-5aea-41a2-9063-5401cf2bffbd" />
