### ISSUE TITLE
updating firmware - nothing works

### ISSUE THREAD

**Issue by Benster1979** [makerbase-mks/MKS-Monster8#11]
I've tried the following to get it to upload a firmware

SD card - doesn't convert to *.CUR (did it once then on reboot, no longer available)
USB Stick - doesn't convert to *.CUR
DFU-Util - Partially

DFU-Util doesn't appear to work with Windows 10 or 11. Tried on various machines.

Did get DFU-Util on pi to upload both the bootloader and the firmware but it still isn't being detected by the pi outside of DFU mode. "ls /dev/serial/by-id/*" via terminal shows no directories. Doesn't matter if I do make menuconfig or not.

I've tried unplugging screen, drivers and removing the UART jumpers

It never detects the board outside of DFU mode. I've also tried loading the klipper.bin via DFU but still no serial device detected.

Thought I might try your Marlin 2x but it doesn't compile due to errors in features/z-align

Please help

**Comment by MKS-hosiey** [comment]
It should be possible to update the firmware with a TF card. Have you checked that your TF card is normal? DFU can work on win10; whether the motherboard is powered by usb to update firmware or switch power supply

**Comment by MarqSolucoes** [comment]
I'm having the same problem, what was the solution?
