### ISSUE TITLE
DIAG jumpers for Sensorless homing

### ISSUE THREAD

**Issue by Sonicboom247** [makerbase-mks/MKS-Monster8#14]
Hello, are the DIAG pins only needed to enable sensorless homing? i am only using sensorless homing on X and Y and BLtouch on Z with TMC 2226 drivers, do I only need DIAG on 0 and 1 or are they needed for anything with a 2226 installed for UART?

**Comment by MKS-hosiey** [comment]
Only need to do it on the axis used

**Comment by Sonicboom247** [comment]
Thank you for the prompt response
