### ISSUE TITLE
How to connect raspberry?

### ISSUE THREAD

**Issue by FabioMiranda10** [makerbase-mks/MKS-Monster8#2]
Is ther a 5v port on the board that supports raspberry pi

**Comment by mks-viva** [comment]
I do not recommend that you supply power to the Raspberry Pi directly from the motherboard

**Comment by mks-viva** [comment]
V2 has a separate 5V power for raspberry

**Comment by Diogynes** [comment]
The V2 5V power supply will not power a Pi over any length of time without under-voltage warnings.  The MP1584E regulator is incapable of sourcing that much current over time.
